### ISSUE TITLE
Not supported for non letters

### ISSUE THREAD

**Issue by kaoxing** [TheD0ubleC/MusicalMoments#1]
I try to use ',' and '.' as switch keys, since when playing games, it is possible that I need to chat with opponents while playing music, but I found out it doesn't work even if I directly modify the userSetting.json. Only letters can be bound as switch keys, I think the problem may be caused by this?
![bug](https://github.com/TheD0ubleC/MusicalMoments/assets/78341741/37331c01-388d-4a6e-a052-bfdeb3cbb6a7)

**Comment by TheD0ubleC** [comment]
Done
