### ISSUE TITLE
功能增加请求

### ISSUE THREAD

**Issue by zxc173123** [TheD0ubleC/MusicalMoments#2]
支持更多的音乐格式，比如flac
能不能改成只要音乐列表有就能播放而不是只能设置一首

**Comment by zxc173123** [comment]
还有麦别人说炸

**Comment by TheD0ubleC** [comment]
暂不支持更多格式，但支持将flac转换为受支持的格式（MP3，WAV）。已正在开发音频独立热键而非指定式音频热键，且移动端音频选择器同样正在开发中，PC端将作为服务端开放服务连接，待移动端连接完成后会将音乐列表同步至移动端，在客户端中按下任意音频列即可操控服务端播放选定音频。关于麦克风含有杂音，目前情况未知，但极大概率是因为VB声卡格式导致，目前在MM中暂未发现缓存溢出问题。如您可以帮助调查原因请上传您的设备信息，媒体设备信息及可能出现问题的代码片段。

**Comment by TheD0ubleC** [comment]
已新增单独音频热键
